parameters :    
    app.path.product_images: /images/archives


vich_uploader:
    db_driver: orm

    mappings:
        archives:
            uri_prefix: '%app.path.product_images%'
            upload_destination: '%kernel.project_dir%/public/%app.path.product_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
